default_language_version:
  python: python3.11
minimum_pre_commit_version: '2.20.0'

ci:
  autoupdate_branch: 'pre-commit/autoupdate'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: ['--py310-plus']
  - repo: https://github.com/PyCQA/isort
    rev: '8.0.1'
    hooks:
      - id: isort
        args: ['--filter-files', '--settings-file', 'pyproject.toml']
  - repo: https://github.com/psf/black
    rev: '26.5.1'
    hooks:
      - id: black
        args: ['--config', 'pyproject.toml']
  - repo: https://github.com/PyCQA/flake8
    rev: '7.3.0'
    hooks:
      - id: flake8
        args: ['--config', '.flake8']
  - repo: https://github.com/aio-libs/sort-all
    rev: 'v1.3.0'
    hooks:
      - id: sort-all
        exclude: ^(\.github)/
        types: []  # Overwrite with empty in order to fallback to types_or
        types_or: [python, pyi]
  - repo: https://github.com/pdm-project/pdm
    rev: '2.27.0'
    hooks:
      - id: pdm-lock-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v6.0.0'
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
