default_language_version:
  python: python3.11
minimum_pre_commit_version: '2.20.0'

ci:
  skip: [mypy]
  autoupdate_branch: 'pre-commit/autoupdate'
  autoupdate_schedule: quarterly

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy (project)
        entry: mypy --config-file=pyproject.toml src
        language: system
        files: ^(src/)
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
      - id: mypy
        name: mypy (tests)
        files: ^((src|tests)/)
        entry: mypy --config-file=pyproject.toml tests
        language: system
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
  - repo: https://github.com/PyCQA/isort
    rev: '5.13.2'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: isort
        args: ['--filter-files', '--settings-file', 'pyproject.toml']
  - repo: https://github.com/psf/black
    rev: '23.12.1'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: black
        args: ['--config', 'pyproject.toml']
  - repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: flake8
        args: ['--config', '.flake8']
  - repo: https://github.com/aio-libs/sort-all
    rev: 'v1.2.0'
    hooks:
      - id: sort-all
        exclude: ^(\.github)/
        types: []  # Overwrite with empty in order to fallback to types_or
        types_or: [python, pyi]
  - repo: https://github.com/pdm-project/pdm
    rev: '2.11.1'
    hooks:
      - id: pdm-lock-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
