[tox]
minversion = 4.55
envlist = mypy-{project,tests}, py3{10,11,12,13,14}, coverage
skip_missing_interpreters = true

[base]
setenv =
    PYTHONHASHSEED = 100

[testenv]
wheel_build_env = {package_env}
pylock = pylock.toml

[testenv:py3{10,11,12,13,14}]
dependency_groups =
    test
    coverage
setenv =
    {[base]setenv}
    COVERAGE_FILE=.coverage.{envname}
commands =
    pytest -p 'no:cacheprovider' {tty:--color=yes} {posargs:--cov --cov-report=''}

[testenv:coverage]
skip_install = True
depends = py3{9,10,11,12}
parallel_show_output = True
dependency_groups =
    coverage
setenv =
    {[base]setenv}
    COVERAGE_FILE=.coverage
commands =
    coverage combine
    coverage report


[testenv:mypy-{project,tests}]
package = wheel
extras =
    mypy
setenv =
    {[base]setenv}
    MYPY_CACHE_DIR = {envtmpdir}{/}.mypy_cache
    MYPY_OPTS = --config-file {toxinidir}{/}pyproject.toml
commands =
    # package
    project: mypy {env:MYPY_OPTS} -p async_object
    # tests
    test: mypy {env:MYPY_OPTS} {toxinidir}{/}tests
