name: Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'tox.ini'
      - 'pylock.toml'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - 'src/**'
      - 'tests/**'
      - '!**.pyi'
      - 'tox.ini'
      - 'pylock.toml'
      - 'pyproject.toml'
      - '.github/workflows/test.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft != true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]
        python_version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        include:
          - python_version: '3.10'
            tox_py: py310
          - python_version: '3.11'
            tox_py: py311
          - python_version: '3.12'
            tox_py: py312
          - python_version: '3.13'
            tox_py: py313
          - python_version: '3.14'
            tox_py: py314

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          check-latest: true
          pip-install: --group=tox
          python-version: ${{ matrix.python_version }}
      - name: mypy checks
        run: tox run -f mypy
      - name: Launch tests
        run: tox run -f ${{ matrix.tox_py }}
